#ServerProperties
server:
  port: 8080
  servlet:
    context-path:

#SpringProperties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql@1234
# MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: 18149318053@163.com
    password: QHMLZWQUVZDQOJSA
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
#redisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
#kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: Community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
#elasticsearchProperties
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: http://localhost:9200
#TaskSchedulingProperties
  task:
    scheduling:
      pool:
        size: 5
#QuartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
# ThymeleafProperties
#thymeleaf是一个模板引擎，缓存的意思是加载一次模板之后便不会再加载了，
#对于生产环境应该加上缓存，但是在开发过程中如果打开缓存，不方便开发人员调试。
#（试想一下，改一行html，就需要重启服务器，肯定是不方便的）
  thymeleaf:
    cache: true

#MybatisProperties
mybatis:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    database-id:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fangzhe.community.entity

# communityProperties
community:
  path:
    domain: http://180.76.190.203
    upload: /tmp/uploads

#wk
wk:
  image:
    command: /opt/wkhtmltoimage.sh
    storage: /tmp/wk-images
#caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180
#spring actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: info,caches
#qiniu properties
qiniu:
    key:
      secret: UeU723EDOBFnNsAqmBX0-AysIeZ6aMHlPTIuMcTH
      access: KWcmAUv8Mw1JkASZorjfdUjDkoqQt5j6hD_ddUvT
    bucket:
      header:
        name: community-fangzhe-header
        url: http://r65svr0ge.hb-bkt.clouddn.com
      share:
        name: community-fangzhe-share
        url: http://r65s9hc81.hb-bkt.clouddn.com