#ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

#SpringProperties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
# MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: 18149318053@163.com
    password: QHMLZWQUVZDQOJSA
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
#redisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
#kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: Community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
#elasticsearchProperties
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: http://localhost:9200
#TaskSchedulingProperties
  task:
    scheduling:
      pool:
        size: 5
#QuartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

#MybatisProperties
mybatis:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    database-id:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fangzhe.community.entity

#上传头像到本地废弃
# communityProperties
community:
  path:
    domain: http://localhost:8080
    upload: d:/work/data/upload

#wk
wk:
  image:
    command: d:/Program/wkhtmltopdf/bin/wkhtmltoimage
    storage: d:/work/data/wk-images
#caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180
##打印日志级别(logback-spring.xml)
#logging:
#  level:
#    com.fangzhe.community: debug
#spring actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: info,caches
#qiniu properties
qiniu:
    key:
      secret: UeU723EDOBFnNsAqmBX0-AysIeZ6aMHlPTIuMcTH
      access: KWcmAUv8Mw1JkASZorjfdUjDkoqQt5j6hD_ddUvT
    bucket:
      header:
        name: community-fangzhe-header
        url: http://r65svr0ge.hb-bkt.clouddn.com
      share:
        name: community-fangzhe-share
        url: http://r65s9hc81.hb-bkt.clouddn.com